language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
  - npm i -g npm@^6.7.0
before_script:
  - npm prune
script:
  - yarn test
after_success:
  - yarn semantic-release
