language: node_js
node_js:
  - "lts/*"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
deploy:
  provider: script
  script: "git checkout master; yarn lerna version --conventional-commits --yes"
  skip_cleanup: true
  on:
    node: "lts/*"
    branch: develop
